// const puppeteer = require('puppeteer');
// const $ = require('cheerio');
// const url = 'https://draftsim.com/M20-pick-order.php';

// let picks = []

const pickOrder = {
    'Nightpack Ambusher': '1',
    'Chandra, Awakened Inferno': '2',
    'Gargos, Vicious Watcher': '3',
    'Vivien, Arkbow Ranger': '4',
    'Ajani, Strength of the Pride': '5',
    'Cavalier of Gales': '6',
    'Cavalier of Night': '7',
    'Cavalier of Flame': '8',
    'Yarok, the Desecrated': '9',
    'Mu Yanling, Sky Dancer': '10',
    'Voracious Hydra': '11',
    'Drakuseth, Maw of Flames': '12',
    'Cavalier of Dawn': '13',
    'Dungeon Geists': '14',
    'Dread Presence': '15',
    'Shifting Ceratops': '16',
    'Omnath, Locus of the Roil': '17',
    'Kykar, Wind\'s Fury': '18',
    'Atemsis, All-Seeing': '19',
    'Cavalier of Thorns': '20',
    'Hanged Executioner': '21',
    'Agent of Treachery': '22',
    'Knight of the Ebon Legion': '23',
    'Kaalia, Zenith Seeker': '24',
    'Risen Reef': '25',
    'Sephara, Sky\'s Blade': '26',
    'Loxodon Lifechanter': '27',
    'Chandra, Novice Pyromancer': '28',
    'Rotting Regisaur': '29',
    'Golos, Tireless Pilgrim': '30',
    'Master Splicer': '31',
    Gravedigger: '32',
    Shock: '33',
    'Bag of Holding': '34',
    'Air Elemental': '35',
    'Tomebound Lich': '36',
    'Cloudkin Seer': '37',
    Murder: '38',
    'Steel Overseer': '39',
    'Moldervine Reclamation': '40',
    'Empyrean Eagle': '41',
    'Ironroot Warlord': '42',
    'Chandra, Acolyte of Flame': '43',
    'Rabid Bite': '44',
    'Chandra\'s Outrage': '45',
    'Howling Giant': '46',
    'Meteor Golem': '47',
    'Lightning Stormkin': '48',
    'Spectral Sailor': '49',
    'Mask of Immolation': '50',
    'Scholar of the Ages': '51',
    'Planar Cleansing': '52',
    Disfigure: '53',
    'Creeping Trailblazer': '54',
    'Glint-Horn Buccaneer': '55',
    'Rapacious Dragon': '56',
    Pacifism: '57',
    'Thrashing Brontodon': '58',
    'Angel of Vitality': '59',
    'Agonizing Syphon': '60',
    'Gorging Vulture': '61',
    Overcome: '62',
    'Blood for Bones': '63',
    'Frost Lynx': '64',
    'Leafkin Druid': '65',
    'Ogre Siegebreaker': '66',
    'Bloodthirsty Aerialist': '67',
    'Masterful Replication': '68',
    'Captivating Gyre': '69',
    'Barkhide Troll': '70',
    'Ember Hauler': '71',
    'Corpse Knight': '72',
    'Yarok\'s Fenlurker': '73',
    'Wakeroot Elemental': '74',
    'Warden of Evos Isle': '75',
    'Skyknight Vanguard': '76',
    'Audacious Thief': '77',
    'Drawn from Dreams': '78',
    'Pulse of Murasa': '79',
    'Overgrowth Elemental': '80',
    'Starfield Mystic': '81',
    'Griffin Protector': '82',
    'Boreal Elemental': '83',
    'Gruesome Scourger': '84',
    'Vengeful Warchief': '85',
    'Pattern Matcher': '86',
    'Scampering Scorcher': '87',
    'Apostle of Purifying Light': '88',
    'Brought Back': '89',
    'Yarok\'s Wavecrasher': '90',
    'Embodiment of Agonies': '91',
    'Bloodsoaked Altar': '92',
    'Noxious Grasp': '93',
    'Winged Words': '94',
    'Vilis, Broker of Blood': '95',
    'Elvish Reclaimer': '96',
    'Woodland Champion': '97',
    'Vampire of the Dire Moon': '98',
    'Sorin, Imperious Bloodlord': '99',
    'Loyal Pegasus': '100',
    'Silverback Shaman': '101',
    'Chandra\'s Spitfire': '102',
    'Dawning Angel': '103',
    'Fencing Ace': '104',
    'Metropolis Sprite': '105',
    'Sleep Paralysis': '106',
    'Reduce to Ashes': '107',
    'Centaur Courser': '108',
    'Might of the Masses': '109',
    'Sedge Scorpion': '110',
    'Ancestral Blade': '111',
    'Aerial Assault': '112',
    'Thicket Crasher': '113',
    'Lavakin Brawler': '114',
    'Goblin Smuggler': '115',
    'Icon of Ancestry': '116',
    'Cerulean Drake': '117',
    'Manifold Key': '118',
    'Renowned Weaponsmith': '119',
    Fry: '120',
    'Marauding Raptor': '121',
    'Herald of the Sun': '122',
    'Season of Growth': '123',
    'Wolfrider\'s Saddle': '124',
    'Bone Splinters': '125',
    'Legion\'s End': '126',
    'Aether Gust': '127',
    Unsummon: '128',
    'Chandra\'s Embercat': '129',
    'Devout Decree': '130',
    'Cryptic Caves': '131',
    'Evolving Wilds': '132',
    'Thornwood Falls': '133',
    'Blossoming Sands': '134',
    'Wind-Scarred Crag': '135',
    'Rugged Highlands': '136',
    'Jungle Hollow': '137',
    'Bloodfell Caves': '138',
    'Swiftwater Cliffs': '139',
    'Dismal Backwater': '140',
    'Scoured Barrens': '141',
    'Tranquil Cove': '142',
    'Griffin Sentinel': '143',
    'Steadfast Sentry': '144',
    'Soul Salvage': '145',
    'Keldon Raider': '146',
    'Gift of Paradise': '147',
    'Mammoth Spider': '148',
    'Netcaster Spider': '149',
    'Gods Willing': '150',
    'Eternal Isolation': '151',
    'Shared Summons': '152',
    'Squad Captain': '153',
    'Boneclad Necromancer': '154',
    'Raise the Alarm': '155',
    'Temple of Triumph': '156',
    'Temple of Epiphany': '157',
    'Temple of Malady': '158',
    'Temple of Mystery': '159',
    'Temple of Silence': '160',
    'Portal of Sanctuary': '161',
    'Repeated Reverberation': '162',
    'Unchained Berserker': '163',
    'Destructive Digger': '164',
    'Uncaged Fury': '165',
    Octoprophet: '166',
    'Flame Sweep': '167',
    'Chandra\'s Regulator': '168',
    'Brightwood Tracker': '169',
    'Gauntlets of Light': '170',
    'Fathom Fleet Cutthroat': '171',
    'Daggersail Aeronaut': '172',
    'Ripscale Predator': '173',
    'Brineborn Cutthroat': '174',
    'Pack Mastiff': '175',
    'Kethis, the Hidden Hand': '176',
    'Wolfkin Bond': '177',
    'Ferocious Pup': '178',
    'Diamond Knight': '179',
    'Heart-Piercer Bow': '180',
    Scuttlemutt: '181',
    'Loaming Shaman': '182',
    'Bishop of Wings': '183',
    Blightbeetle: '184',
    'Veil of Summer': '185',
    Infuriate: '186',
    'Glaring Aegis': '187',
    Befuddle: '188',
    'Frilled Sea Serpent': '189',
    'Epicure of Blood': '190',
    'Sanitarium Skeleton': '191',
    'Feral Invocation': '192',
    'Marauder\'s Axe': '193',
    'Battalion Foot Soldier': '194',
    'Faerie Miscreant': '195',
    'Blood Burglar': '196',
    'Lotus Field': '197',
    'Vial of Dragonfire': '198',
    'Hard Cover': '199',
    'Growth Cycle': '200',
    'Retributive Wand': '201',
    'Goblin Bird-Grabber': '202',
    'Angelic Gift': '203',
    'Daybreak Chaplain': '204',
    'Inspiring Captain': '205',
    'Moment of Heroism': '206',
    'Moorland Inquisitor': '207',
    Anticipate: '208',
    'Sage\'s Row Denizen': '209',
    'Zephyr Charge': '210',
    'Barony Vampire': '211',
    Bladebrand: '212',
    'Feral Abomination': '213',
    'Mind Rot': '214',
    'Sorcerer of the Fang': '215',
    'Fire Elemental': '216',
    'Scorch Spitter': '217',
    Prismite: '218',
    Vorstclaw: '219',
    'Undead Servant': '220',
    'Moat Piranhas': '221',
    Convolute: '222',
    'Goblin Ringleader': '223',
    'Dragon Mage': '224',
    Negate: '225',
    'Inspired Charge': '226',
    Soulmender: '227',
    'Bone to Ash': '228',
    'Fortress Crab': '229',
    Duress: '230',
    'Maniacal Rage': '231',
    'Tectonic Rift': '232',
    'Greenwood Sentinel': '233',
    Plummet: '234',
    'Anvilwrought Raptor': '235',
    'Thunderkin Awakener': '236',
    'Tale\'s End': '237',
    'Colossus Hammer': '238',
    'Leyline of Abundance': '239',
    'Leyline of Anticipation': '240',
    'Reckless Air Strike': '241',
    'Leyline of Combustion': '242',
    Disenchant: '243',
    'Scheming Symmetry': '244',
    'Yoked Ox': '245',
    'Act of Treason': '246',
    'Healer of the Glade': '247',
    'Natural End': '248',
    'Salvager of Ruin': '249',
    'Diviner\'s Lockbox': '250',
    'Field of the Dead': '251',
    'Flood of Tears': '252',
    'Leyline of Sanctity': '253',
    'Unholy Indenture': '254',
    'Stone Golem': '255',
    'Mystic Forge': '256',
    'Rule of Law': '257',
    'Leyline of the Void': '258',
    'Grafdigger\'s Cage': '259',
    'Thought Distortion': '260',
    'Forest 4': '261',
    'Forest 3': '262',
    'Forest 2': '263',
    'Forest 1': '264',
    'Mountain 4': '265',
    'Mountain 3': '266',
    'Mountain 2': '267',
    'Mountain 1': '268',
    'Swamp 4': '269',
    'Swamp 3': '270',
    'Swamp 2': '271',
    'Swamp 1': '272',
    'Island 4': '273',
    'Island 3': '274',
    'Island 2': '275',
    'Island 1': '276',
    'Plains 4': '277',
    'Plains 3': '278',
    'Plains 2': '279',
    'Plains 1': '280' 
}

// puppeteer
// .launch()
// .then(function(browser) {
//     return browser.newPage();
// })
// .then(function(page) {
//     return page.goto(url).then(function() {
//         return page.content();
//     });
// })
// .then(function(html) {
//     $('.card_label', html).each(function() {
//         picks.push($(this).text());
//     })
//     picks.forEach(pick => {
//         let tempArr = pick.split('. ');
//         pickOrder[tempArr[1]] = tempArr[0];
//     })
//     console.log(pickOrder)
// })
// .catch(function(err) {
    
// });


module.exports = pickOrder;